/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    Row: typeof import('./src/components/row.vue')['default']
    Waterfall: typeof import('./src/components/waterfall.vue')['default']
  }
}
